<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="<?= BASE_URL ?>Style/global.css">
</head>
<header>
    <h1>Reseñitas</h1>
    <h2>Aca recomendamos peliculas gratis, series gratis, documentales gratis online</h2>
    <?php 
        if (isset($req->user)) {
            echo " Usuario: " . $req->user->nombre;
            echo " (" . $req->user->rol . ") |";
        }
    ?>
    <a href="<?= BASE_URL ?>login/signOut">Cerrar sesion</a>
</header>

<body>
    <p> Volver al inicio: <a href="<?= BASE_URL ?>home">Home</a></p>    
    <img src="<?= $pelicula->imagen ?>" alt="pelicula">
    <h2> <?= $pelicula->nombre; ?></h2>
    <h3> Descripcion: <?= $pelicula->descripcion; ?></h3>
    <p> Fecha: <?= $pelicula->fecha; ?></p>
    <p> Esta pelicula pertenece a la categoria: <a href="<?= BASE_URL ?>categorias/verCategoria/<?= $categoria->id ?>"><?= $categoria->nombre ?></p>
</body>
</html>