<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="<?= BASE_URL ?>Style/global.css">
</head>
<body>
    <h1>Register</h1>
    <form method="POST" action="<?= BASE_URL ?>login/registerUser/">
        <label>Nombre:</label><br>
        <input type="text" name="nombre" placeholder="Ingrese nombre de usuario"><br>

        <label>Contraseña:</label><br>
        <input type="password" name="contraseña" placeholder="Ingrese contraseña"><br>

        <button type="submit" name="btnEnviar">Registrarse</button><br>
        <button><a href="<?= BASE_URL ?>login/">Iniciar Sesion</a></button>
    </form>


</body>
</html>